@extends('layouts.app')

@section('title', 'Homepage')

@section('content')
    <h1 class="align-items-center">Hello, world!</h1><br>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum, velit id vestibulum condimentum, nibh quam ultricies ante, sed hendrerit dui odio quis nisl. Maecenas sed ipsum in elit malesuada auctor id ornare turpis. Mauris porttitor diam eu arcu sagittis lobortis. Nam quis eros bibendum, sollicitudin quam quis, cursus libero. Vestibulum hendrerit nec lacus varius maximus. Ut eget lectus placerat, porta felis a, mattis augue. Nullam ut vehicula diam, sit amet elementum nisl. Morbi fringilla efficitur urna in gravida. Nunc scelerisque venenatis vehicula. Maecenas sit amet leo libero. Maecenas sed neque vel sapien suscipit fermentum ac at mauris.</p>
    <p>Phasellus a dolor eget enim rhoncus ornare. Sed malesuada eget odio a aliquam. Vestibulum semper sapien et neque condimentum, in dapibus est consectetur. Aenean euismod semper libero quis vulputate. Phasellus semper malesuada mattis. Phasellus ultricies faucibus ipsum, in mattis libero semper a. Vestibulum sit amet lectus rhoncus, varius tortor in, interdum lorem. Quisque pellentesque tempor erat, vitae hendrerit ante suscipit quis. Donec vitae risus felis. Sed ac laoreet quam. Quisque et tellus a enim rhoncus egestas ut et erat. Curabitur tincidunt et magna quis accumsan. Fusce placerat dolor quis sem malesuada, non sodales nisl commodo. In ut mattis sapien, sed imperdiet turpis.</p>
    <p>Proin a lectus dignissim, efficitur ipsum quis, dapibus dui. Praesent accumsan, ante non molestie aliquam, tortor justo pharetra nisi, id vestibulum tellus nibh vel arcu. In vel nisi at diam elementum aliquet eu sed sem. Nam at ante at sapien pharetra luctus ut id neque. Sed eu lacus eros. Nunc tempus quam at urna sollicitudin scelerisque. Sed ullamcorper, turpis a tristique egestas, purus erat rutrum tellus, non aliquam neque metus et mi. Vestibulum vel interdum ipsum, quis posuere purus. Aliquam mi neque, facilisis sit amet orci ut, luctus blandit sem. Morbi semper metus eget odio luctus, non luctus lorem sodales. Quisque eget lorem dapibus, rutrum diam id, consequat nibh. Aliquam facilisis egestas nulla ac iaculis.</p>
    <p>Nulla tincidunt pellentesque mauris sit amet tincidunt. Curabitur quam odio, pharetra eu elit non, elementum facilisis orci. Nulla facilisi. Ut in ligula tempus, mollis nulla ac, semper sapien. Donec posuere, nunc sit amet egestas venenatis, nibh dui suscipit tellus, sit amet mollis nulla augue quis lorem. Nullam auctor fermentum sodales. Integer blandit sem nec luctus pulvinar. Donec in libero iaculis, tincidunt augue sit amet, elementum erat.</p>
    <p>Cras mollis nulla a ante sollicitudin, vel volutpat nibh molestie. Pellentesque mollis lobortis eros, et efficitur urna viverra gravida. Sed cursus nisl non orci facilisis bibendum. Integer imperdiet, purus ac fermentum consectetur, dolor erat sollicitudin tellus, vitae malesuada mi erat in neque. Duis tincidunt massa dolor, eu laoreet ante auctor sit amet. Vivamus non rutrum metus. Donec quam ligula, efficitur vitae ligula at, gravida tincidunt sem. Fusce suscipit lacus sit amet vulputate malesuada. Proin turpis eros, efficitur cursus neque a, semper tristique orci. Etiam bibendum pretium neque vel varius. Nunc vitae varius ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer euismod erat justo, ac finibus quam porttitor et. Aenean elit eros, tincidunt eget augue vitae, pellentesque pretium nunc. Maecenas tempus urna elit, eu interdum risus lacinia sed. Curabitur egestas odio tellus, vel efficitur metus ornare interdum.</p>
@endsection

@section('side')
    @parent
    <p>You are at home!</p>
@endsection
